// Everyday-object vocabulary + offline knowledge base, built into public/models/objects-kb.json.
// Each entry: [name, Hindi name, category, what it's used for, one useful/safety tip, Caltech-256 labels?]
// Names double as CLIP prompts, so they're phrased the way people describe the thing.
import { writeFileSync } from "node:fs";

const V = [
  // personal & carry
  ["mobile phone", "मोबाइल फ़ोन", "personal", "Calls, messages, internet, UPI payments and photos.", "Keep it away from water and heat; lock it with a PIN or fingerprint."],
  ["wallet", "बटुआ", "personal", "Holds cash, cards and ID.", "Carry only the cards you need; keep a photo of your IDs in case it's lost."],
  ["keys", "चाबियाँ", "personal", "Open locks for the home, vehicle or cupboard.", "Keep a spare key with someone you trust."],
  ["eyeglasses", "चश्मा", "personal", "Correct vision or protect the eyes.", "Clean lenses with a microfiber cloth, not a shirt, to avoid scratches.", ["eyeglasses"]],
  ["sunglasses", "धूप का चश्मा", "personal", "Protect eyes from bright sunlight and UV.", "Choose lenses marked UV400 for real UV protection."],
  ["wrist watch", "कलाई घड़ी", "personal", "Shows the time; smartwatches also track health.", "Remove it before swimming unless it is rated water-resistant.", ["watch-101"]],
  ["backpack", "बैग / बस्ता", "personal", "Carries books, laptop and daily items.", "Use both straps and keep heavy items close to your back.", ["backpack"]],
  ["handbag", "हैंडबैग", "personal", "Carries personal items when going out.", "Zip it shut in crowded places."],
  ["umbrella", "छाता", "personal", "Protection from rain and strong sun.", "Dry it open before folding so it doesn't rust or smell.", ["umbrella-101"]],
  ["water bottle", "पानी की बोतल", "personal", "Carries drinking water.", "Wash it daily; steel bottles are better than reusing thin plastic ones."],
  ["id card", "पहचान पत्र", "personal", "Proves identity, like Aadhaar, PAN or a college ID.", "Never share a full photo of your Aadhaar; use the masked version."],
  ["credit card", "क्रेडिट कार्ड", "personal", "Cashless payments and online shopping.", "Never share the OTP or CVV with anyone, even if they claim to be the bank."],
  ["coin", "सिक्का", "personal", "Small-value money.", "Keep coins away from small children; they are a choking hazard.", ["coin"]],
  ["banknote", "नोट (रुपया)", "personal", "Paper money for payments.", "Check the security thread and watermark if a note looks suspicious."],
  ["comb", "कंघी", "personal", "Untangles and styles hair.", "Don't share combs, to avoid spreading lice or scalp infections."],
  ["hair dryer", "हेयर ड्रायर", "personal", "Dries hair with warm air.", "Keep it away from water and unplug it after use."],
  ["perfume bottle", "इत्र की शीशी", "personal", "Adds fragrance.", "Store away from sunlight so the scent lasts longer."],
  ["lipstick", "लिपस्टिक", "personal", "Colours the lips.", "Replace it after about a year; old makeup can grow bacteria."],
  ["necktie", "टाई", "clothing", "Formal wear with a shirt.", "Hang ties instead of folding them to avoid creases.", ["necktie"]],
  ["cap", "टोपी", "clothing", "Shades the face from the sun.", "Wear one outdoors in summer to lower the risk of heatstroke."],
  ["t-shirt", "टी-शर्ट", "clothing", "Everyday casual clothing.", "Wash dark colours inside out to keep them from fading.", ["t-shirt"]],
  ["socks", "मोज़े", "clothing", "Keep feet warm and dry inside shoes.", "Change socks daily to prevent fungal infections.", ["socks"]],
  ["shoes", "जूते", "clothing", "Protect the feet while walking.", "Air them out regularly; damp shoes cause odour and fungus.", ["sneaker", "tennis-shoes"]],
  ["slippers", "चप्पल", "clothing", "Comfortable footwear at home.", "Choose ones with a good grip for wet bathroom floors."],
  ["saree", "साड़ी", "clothing", "Traditional Indian women's garment.", "Store silk sarees in cotton cloth, not plastic."],
  ["helmet", "हेलमेट", "safety", "Protects the head on a two-wheeler.", "Always strap it; an unbuckled helmet can come off in a crash."],
  ["face mask", "मास्क", "health", "Reduces the spread of germs and dust.", "It should cover both nose and mouth; replace disposable ones daily."],

  // electronics
  ["laptop", "लैपटॉप", "electronics", "Work, study, coding and entertainment.", "Don't block the air vents; overheating shortens its life.", ["laptop-101"]],
  ["computer keyboard", "कीबोर्ड", "electronics", "Typing text into a computer.", "Clean it with compressed air; crumbs cause sticky keys.", ["computer-keyboard"]],
  ["computer mouse", "माउस", "electronics", "Points and clicks on a computer screen.", "A mouse pad improves tracking on shiny surfaces.", ["computer-mouse"]],
  ["computer monitor", "मॉनिटर", "electronics", "Displays the computer's output.", "Keep the top of the screen at eye level to protect your neck.", ["computer-monitor"]],
  ["television", "टीवी", "electronics", "Shows TV channels and streaming apps.", "Sit at least 2 metres away and keep the room lit to reduce eye strain."],
  ["tv remote", "टीवी रिमोट", "electronics", "Controls the TV or set-top box from a distance.", "Remove batteries if unused for months to prevent leaks."],
  ["phone charger", "फ़ोन चार्जर", "electronics", "Charges a phone's battery.", "Use a certified charger; cheap ones can overheat and damage the phone."],
  ["power bank", "पावर बैंक", "electronics", "Portable battery to charge phones on the go.", "Don't leave it charging overnight or in a hot car."],
  ["earphones", "ईयरफ़ोन", "electronics", "Listen to audio privately.", "Keep volume below 60% to protect your hearing."],
  ["headphones", "हेडफ़ोन", "electronics", "Over-ear audio for music and calls.", "Take breaks every hour; long loud listening damages hearing.", ["head-phones"]],
  ["bluetooth speaker", "ब्लूटूथ स्पीकर", "electronics", "Plays music wirelessly from a phone.", "Keep it charged between 20% and 80% for a longer battery life."],
  ["tablet", "टैबलेट", "electronics", "Portable touchscreen for reading and video.", "Enable parental controls if children use it."],
  ["camera", "कैमरा", "electronics", "Takes photos and videos.", "Keep the lens cap on when not shooting."],
  ["calculator", "कैलकुलेटर", "electronics", "Quick arithmetic.", "Solar calculators work best near a window.", ["calculator"]],
  ["usb cable", "यूएसबी केबल", "electronics", "Charges devices and transfers data.", "Don't bend it sharply at the plug; that's where it breaks first."],
  ["extension board", "एक्सटेंशन बोर्ड", "electronics", "Gives more power sockets.", "Don't plug heaters or ACs into it; overload can start a fire."],
  ["light bulb", "बल्ब", "home", "Lights up a room.", "LED bulbs use about 80% less electricity than old bulbs.", ["lightbulb"]],
  ["flashlight", "टॉर्च", "home", "Portable light for the dark or power cuts.", "Keep one with working batteries for emergencies.", ["flashlight"]],
  ["ceiling fan", "पंखा", "home", "Circulates air to cool the room.", "Clean the blades monthly; dust makes the motor work harder."],
  ["air conditioner", "एसी", "home", "Cools and dries indoor air.", "24–26°C saves a lot of electricity with little loss of comfort."],
  ["refrigerator", "फ्रिज", "kitchen", "Keeps food fresh and cold.", "Don't put hot food straight in; let it cool first.", ["refrigerator"]],
  ["washing machine", "वॉशिंग मशीन", "home", "Washes clothes automatically.", "Leave the door open after use so it dries and doesn't smell.", ["washing-machine"]],
  ["microwave oven", "माइक्रोवेव", "kitchen", "Heats and cooks food quickly.", "Never put metal or steel utensils inside.", ["microwave"]],
  ["toaster", "टोस्टर", "kitchen", "Toasts bread.", "Unplug it before removing stuck bread; never use a knife inside.", ["toaster"]],
  ["electric kettle", "इलेक्ट्रिक केतली", "kitchen", "Boils water quickly.", "Descale it with vinegar or lemon every few weeks."],
  ["mixer grinder", "मिक्सर ग्राइंडर", "kitchen", "Grinds masalas and makes chutney and batter.", "Don't fill it more than half with hot liquids."],
  ["induction cooktop", "इंडक्शन चूल्हा", "kitchen", "Cooks with electricity using magnetic heating.", "Works only with flat-bottomed steel or iron pans."],
  ["gas stove", "गैस चूल्हा", "kitchen", "Cooks food on an LPG flame.", "Turn off the cylinder regulator at night; if you smell gas, don't switch on lights."],
  ["gas cylinder", "गैस सिलेंडर", "kitchen", "Stores LPG cooking gas.", "Keep it upright and check the pipe for cracks every few months."],
  ["iron", "इस्त्री", "home", "Removes wrinkles from clothes.", "Never leave it face down and switched on."],
  ["vacuum cleaner", "वैक्यूम क्लीनर", "home", "Sucks up dust from floors and sofas.", "Empty the dust bag before it's full to keep the suction strong."],
  ["smoke detector", "स्मोक डिटेक्टर", "safety", "Beeps loudly when it senses smoke.", "Test it monthly with its button."],
  ["fire extinguisher", "अग्निशामक यंत्र", "safety", "Puts out small fires.", "Remember PASS: Pull the pin, Aim at the base, Squeeze, Sweep.", ["fire-extinguisher"]],
  ["router", "वाई-फ़ाई राउटर", "electronics", "Shares the internet over Wi-Fi.", "Change the default password and place it centrally for better signal."],
  ["printer", "प्रिंटर", "electronics", "Prints documents and photos.", "Print a page every week or two so the ink doesn't dry up.", ["photocopier"]],
  ["projector", "प्रोजेक्टर", "electronics", "Shows a large picture on a wall.", "Let it cool down before unplugging.", ["video-projector"]],
  ["game controller", "गेम कंट्रोलर", "electronics", "Controls video games.", "Take a 10-minute break every hour of gaming.", ["joy-stick"]],
  ["music player", "म्यूज़िक प्लेयर", "electronics", "Plays stored music.", "Keep the volume moderate to protect your ears.", ["ipod"]],
  ["landline telephone", "टेलीफ़ोन", "electronics", "Voice calls over a phone line.", "Keep emergency numbers written next to it.", ["rotary-phone"]],
  ["cd", "सीडी", "electronics", "Stores music, films or data on a disc.", "Hold discs by the edges to avoid scratches.", ["cd"]],

  // kitchen & food
  ["pressure cooker", "प्रेशर कुकर", "kitchen", "Cooks dal, rice and vegetables fast under steam pressure.", "Check the gasket and whistle before cooking; never open it while pressurised."],
  ["frying pan", "फ्राइंग पैन", "kitchen", "Frying and sautéing.", "Use wooden or silicone spatulas on non-stick pans.", ["frying-pan"]],
  ["tawa", "तवा", "kitchen", "Flat griddle for rotis, parathas and dosas.", "Season an iron tawa with a little oil after washing so it doesn't rust."],
  ["kadai", "कड़ाही", "kitchen", "Deep wok for frying and curries.", "Don't reuse deep-frying oil more than once or twice."],
  ["cooking pot", "पतीला", "kitchen", "Boils milk, tea, rice and curries.", "Use a lid; it saves up to a third of the cooking gas."],
  ["plate", "थाली / प्लेट", "kitchen", "Holds food for eating.", "Steel and ceramic plates are safer than thin plastic for hot food."],
  ["bowl", "कटोरी", "kitchen", "Holds dal, curry or dessert.", "Wash promptly so food doesn't dry on."],
  ["spoon", "चम्मच", "kitchen", "Eating and serving.", "A teaspoon is about 5 ml, a tablespoon about 15 ml.", ["spoon"]],
  ["fork", "कांटा", "kitchen", "Picks up food.", "Keep forks away from toddlers."],
  ["knife", "चाकू", "kitchen", "Cuts vegetables, fruit and bread.", "A sharp knife is safer than a blunt one; cut away from your body.", ["knife", "swiss-army-knife"]],
  ["chopping board", "चॉपिंग बोर्ड", "kitchen", "A safe surface for cutting food.", "Use separate boards for raw meat and vegetables."],
  ["rolling pin", "बेलन", "kitchen", "Rolls out dough for rotis and puris.", "Dust it with a little flour so dough doesn't stick."],
  ["steel glass", "स्टील का गिलास", "kitchen", "Drinking water, milk or lassi.", "Steel is unbreakable and doesn't leach chemicals."],
  ["coffee mug", "कॉफ़ी मग", "kitchen", "Hot drinks like tea and coffee.", "Chipped ceramic mugs can crack with heat; replace them.", ["coffee-mug", "beer-mug"]],
  ["teapot", "चायदानी", "kitchen", "Brews and serves tea.", "Rinse it well; old tea leaves turn bitter.", ["teapot"]],
  ["tiffin box", "टिफ़िन", "kitchen", "Carries home-cooked lunch.", "Pack hot food only after it cools a little, to avoid sogginess and bacteria."],
  ["lunch box", "लंच बॉक्स", "kitchen", "Carries food to school or office.", "Wash and dry it fully every day."],
  ["jar", "डिब्बा / जार", "kitchen", "Stores spices, pickles or snacks.", "Airtight jars keep snacks crisp and keep insects out."],
  ["salt container", "नमक का डिब्बा", "kitchen", "Stores salt.", "Adults should have less than 5 g of salt a day (WHO)."],
  ["spice box", "मसालेदानी", "kitchen", "Keeps everyday masalas in one place.", "Store spices away from the stove; heat dulls their flavour."],
  ["chopsticks", "चॉपस्टिक", "kitchen", "Eating noodles and East Asian food.", "Don't stick them upright in rice; it's considered rude in many cultures.", ["chopsticks"]],
  ["drinking straw", "स्ट्रॉ", "kitchen", "Sipping drinks.", "Reusable steel or bamboo straws cut plastic waste.", ["drinking-straw"]],
  ["wine bottle", "बोतल", "kitchen", "A glass bottle for drinks.", "Recycle glass separately from other waste.", ["wine-bottle"]],
  ["soda can", "कोल्ड ड्रिंक का कैन", "food", "Packaged soft drink.", "A can of cola has about 7 teaspoons of sugar.", ["soda-can"]],
  ["cereal box", "कॉर्नफ़्लेक्स का डिब्बा", "food", "Breakfast cereal.", "Check the sugar per serving on the label.", ["cereal-box"]],
  ["milk packet", "दूध का पैकेट", "food", "Packaged milk.", "Refrigerate after opening and use it within a day or two."],
  ["bread", "ब्रेड", "food", "Sandwiches and toast.", "Check for mould before eating; store in a cool, dry place."],
  ["egg", "अंडा", "food", "Protein-rich food.", "A fresh egg sinks in water; an old one floats.", ["fried-egg"]],
  ["banana", "केला", "food", "Energy-rich fruit with potassium.", "Keep bananas separate from other fruit; they make them ripen faster."],
  ["apple", "सेब", "food", "Fibre-rich fruit.", "Eat the peel; much of the fibre is there."],
  ["orange", "संतरा", "food", "Juicy fruit rich in vitamin C.", "Whole fruit has more fibre than juice."],
  ["mango", "आम", "food", "India's national fruit.", "Soak mangoes in water for a while before eating."],
  ["tomato", "टमाटर", "food", "Used in curries, salads and chutneys.", "Store at room temperature for better flavour.", ["tomato"]],
  ["onion", "प्याज़", "food", "Base of most Indian curries.", "Store in a dry, airy basket, not the fridge."],
  ["potato", "आलू", "food", "Starchy vegetable for sabzi and snacks.", "Don't eat green or sprouted parts."],
  ["grapes", "अंगूर", "food", "Sweet fruit eaten fresh or dried as raisins.", "Wash well before eating; grapes can carry pesticide residue.", ["grapes"]],
  ["watermelon", "तरबूज़", "food", "Hydrating summer fruit.", "About 90% water, great in hot weather.", ["watermelon"]],
  ["cake", "केक", "food", "Sweet baked dessert.", "Refrigerate cream cakes.", ["cake"]],
  ["burger", "बर्गर", "food", "Bun with a patty and vegetables.", "Fast food is high in salt and fat; best as an occasional treat.", ["hamburger"]],
  ["pizza", "पिज़्ज़ा", "food", "Baked flatbread with cheese and toppings.", "Thin crust with vegetable toppings is lighter."],
  ["ice cream", "आइसक्रीम", "food", "Frozen sweet dessert.", "Don't refreeze melted ice cream.", ["ice-cream-cone"]],
  ["noodles", "नूडल्स", "food", "Quick meal.", "Instant noodles are high in salt; add vegetables for nutrition.", ["spaghetti"]],
  ["biscuit packet", "बिस्कुट का पैकेट", "food", "Packaged snack.", "Check the expiry date and sugar content on the label."],
  ["chocolate", "चॉकलेट", "food", "Sweet treat made from cocoa.", "Dark chocolate has less sugar than milk chocolate."],

  // home & furniture
  ["chair", "कुर्सी", "home", "Sitting.", "Keep your feet flat and back supported to avoid back pain."],
  ["table", "मेज़", "home", "A surface for eating, studying or working.", "Keep sharp corners covered when toddlers are around.", ["picnic-table"]],
  ["bed", "बिस्तर", "home", "Sleeping and resting.", "Adults need 7–9 hours of sleep."],
  ["mattress", "गद्दा", "home", "Soft layer for comfortable sleep.", "Flip or rotate it every few months.", ["mattress"]],
  ["pillow", "तकिया", "home", "Supports the head while sleeping.", "Wash pillow covers weekly."],
  ["blanket", "कंबल", "home", "Keeps you warm.", "Air it in sunlight to freshen it."],
  ["sofa", "सोफ़ा", "home", "Comfortable seating for several people.", "Vacuum under the cushions to remove dust."],
  ["cupboard", "अलमारी", "home", "Stores clothes and valuables.", "A few neem leaves or naphthalene balls keep insects away."],
  ["mirror", "आईना", "home", "Shows your reflection.", "Clean it with newspaper and a little vinegar for a streak-free shine."],
  ["clock", "घड़ी", "home", "Shows the time.", "Replace the battery when it starts running slow."],
  ["door", "दरवाज़ा", "home", "Entrance to a room or house.", "Lock it even when you're at home at night."],
  ["door handle", "हैंडल", "home", "Opens and closes the door.", "One of the most touched surfaces; wipe it regularly.", ["doorknob"]],
  ["window", "खिड़की", "home", "Lets in light and fresh air.", "Open windows daily for ventilation."],
  ["curtain", "पर्दा", "home", "Blocks light and gives privacy.", "Thick curtains help keep rooms cool in summer."],
  ["bucket", "बाल्टी", "home", "Holds water for bathing or cleaning.", "Keep it covered or empty; standing water breeds mosquitoes."],
  ["plastic bath mug", "मग्गा", "home", "Pours water while bathing.", "Rinse and dry it to prevent algae."],
  ["broom", "झाड़ू", "home", "Sweeps the floor.", "Store it upright or hung so the bristles last."],
  ["mop", "पोछा", "home", "Wipes floors clean.", "Add a disinfectant to the mopping water."],
  ["dustbin", "कूड़ेदान", "home", "Holds waste.", "Separate wet and dry waste (green and blue bins)."],
  ["toothbrush", "टूथब्रश", "health", "Cleans teeth.", "Replace it every 3 months, or sooner if the bristles splay."],
  ["toothpaste", "टूथपेस्ट", "health", "Cleans teeth and prevents cavities.", "A pea-sized amount is enough; use fluoride toothpaste."],
  ["soap", "साबुन", "health", "Cleans hands and body, removes germs.", "Wash hands for at least 20 seconds."],
  ["towel", "तौलिया", "home", "Dries the body after bathing.", "Dry it in sunlight and don't share towels."],
  ["shampoo bottle", "शैम्पू", "personal", "Cleans hair.", "Rinse thoroughly; residue can cause dandruff."],
  ["tissue box", "टिश्यू बॉक्स", "home", "Disposable tissues.", "Throw used tissues away right away to stop germs spreading."],
  ["candle", "मोमबत्ती", "home", "Light during power cuts or for decoration.", "Never leave a lit candle unattended."],
  ["diya", "दीया", "home", "Traditional oil lamp for prayers and festivals.", "Keep it away from curtains and paper decorations."],
  ["incense stick", "अगरबत्ती", "home", "Gives fragrance during prayers.", "Ventilate the room; the smoke can irritate lungs."],
  ["plant pot", "गमला", "home", "Grows plants indoors or on a balcony.", "Make sure it has a drain hole so roots don't rot."],
  ["teddy bear", "टेडी बियर", "toys", "Soft toy for comfort and play.", "Wash soft toys regularly; they collect dust mites.", ["teddy-bear"]],
  ["ladder", "सीढ़ी", "tools", "Reaching high places.", "Keep three points of contact and never stand on the top step.", ["ladder"]],
  ["tripod", "ट्राइपॉड", "tools", "Holds a camera or phone steady.", "Hang your bag on its hook for stability in wind.", ["tripod"]],

  // stationery & study
  ["pen", "पेन", "stationery", "Writing.", "Cap it after use so it doesn't dry out."],
  ["pencil", "पेंसिल", "stationery", "Writing and drawing that can be erased.", "HB is best for everyday writing."],
  ["notebook", "कॉपी", "stationery", "Writing notes.", "Date each page; it makes revision easier."],
  ["book", "किताब", "stationery", "Reading and learning.", "Read in good light, about 30 cm from your eyes."],
  ["scissors", "कैंची", "stationery", "Cutting paper and cloth.", "Pass them handle-first and keep them away from small children."],
  ["stapler", "स्टेपलर", "stationery", "Joins sheets of paper.", "Use the right size of staples for your stapler."],
  ["paper clip", "पेपर क्लिप", "stationery", "Holds papers together without damage.", "A handy tool for ejecting phone SIM trays.", ["paperclip"]],
  ["eraser", "रबड़", "stationery", "Removes pencil marks.", "Keep it clean; a dirty eraser smudges."],
  ["ruler", "स्केल", "stationery", "Draws straight lines and measures length.", "A 30 cm ruler equals about one foot."],
  ["envelope", "लिफ़ाफ़ा", "stationery", "Sends letters and documents.", "Write the PIN code clearly for faster delivery."],
  ["playing cards", "ताश", "toys", "Card games.", "A good family game; keep screen time low.", ["playing-card"]],
  ["dice", "पासा", "toys", "Board games like Ludo and Snakes & Ladders.", "The opposite faces of a standard die add up to 7.", ["dice"]],

  // health & medicine
  ["medicine strip", "दवाई का पत्ता", "health", "Tablets or capsules prescribed for illness.", "Check the expiry date; don't stop antibiotics early."],
  ["medicine bottle", "दवाई की शीशी", "health", "Syrup or tablets.", "Measure syrup with the cup provided, not a kitchen spoon."],
  ["thermometer", "थर्मामीटर", "health", "Measures body temperature.", "Normal is about 36.5–37.5°C (97.7–99.5°F)."],
  ["syringe", "सिरिंज", "health", "Gives injections.", "Use a new syringe every time and dispose of it safely.", ["syringe"]],
  ["first aid kit", "फ़र्स्ट एड बॉक्स", "health", "Bandages and medicines for small injuries.", "Check and restock it every six months."],
  ["bandage", "पट्टी", "health", "Covers and protects wounds.", "Clean the wound before covering it."],
  ["pulse oximeter", "ऑक्सीमीटर", "health", "Measures blood oxygen and pulse.", "Below 94% oxygen needs a doctor's advice."],
  ["hand sanitizer", "सैनिटाइज़र", "health", "Kills germs when soap isn't available.", "Use one with at least 60% alcohol; keep it away from flames."],
  ["tweezers", "चिमटी", "health", "Removes splinters and plucks hair.", "Clean them with alcohol before and after use.", ["tweezer"]],
  ["weighing scale", "वज़न मशीन", "health", "Measures body weight.", "Weigh yourself at the same time each day for consistent readings."],
  ["dumbbell", "डम्बल", "sports", "Strength training.", "Warm up first and keep your back straight while lifting.", ["dumb-bell"]],
  ["yoga mat", "योगा मैट", "sports", "Cushions and grips during yoga or exercise.", "Wipe it after use."],
  ["cricket bat", "क्रिकेट बैट", "sports", "Batting in cricket.", "Oil a new willow bat and knock it in before playing."],
  ["football", "फ़ुटबॉल", "sports", "Playing football.", "Check the pressure; an over-inflated ball hurts on impact.", ["soccer-ball"]],
  ["tennis ball", "टेनिस बॉल", "sports", "Tennis and gully cricket.", "Great for practice; wear eye protection for fast play.", ["tennis-ball"]],
  ["badminton racket", "बैडमिंटन रैकेट", "sports", "Playing badminton.", "Store it in a cover away from heat so the strings keep their tension."],
  ["skipping rope", "रस्सी", "sports", "Cardio exercise.", "Jump on a soft surface to protect your knees."],
  ["treadmill", "ट्रेडमिल", "sports", "Walking or running indoors.", "Clip the safety key to your clothes.", ["treadmill"]],

  // tools & DIY
  ["screwdriver", "पेचकस", "tools", "Tightens and loosens screws.", "Match the tip to the screw head so it doesn't slip.", ["screwdriver"]],
  ["hammer", "हथौड़ा", "tools", "Drives nails.", "Hold it near the end of the handle for more force and control."],
  ["pliers", "प्लास", "tools", "Grips, bends and cuts wire.", "Use insulated pliers for electrical work."],
  ["tape measure", "इंची टेप", "tools", "Measures length.", "Lock it before reading; let it retract slowly."],
  ["drill machine", "ड्रिल मशीन", "tools", "Drills holes in walls and wood.", "Check for hidden wires before drilling a wall."],
  ["padlock", "ताला", "tools", "Locks doors, gates and luggage.", "Oil it once a year so it doesn't jam."],
  ["sewing needle", "सुई", "tools", "Stitches cloth.", "Store needles in a pincushion, not loose in a drawer."],

  // outdoors & vehicles
  ["bicycle", "साइकिल", "vehicles", "Eco-friendly transport and exercise.", "Wear a helmet and use lights at night.", ["mountain-bike", "touring-bike"]],
  ["motorcycle", "मोटरसाइकिल", "vehicles", "Two-wheeler transport.", "Always wear a helmet; it cuts the risk of head injury by around 70%.", ["motorbikes-101"]],
  ["scooter", "स्कूटी", "vehicles", "Easy-to-ride two-wheeler.", "Check tyre pressure every two weeks."],
  ["car", "कार", "vehicles", "Four-wheeler transport.", "Everyone, including rear passengers, should wear a seat belt.", ["car-side-101"]],
  ["car tyre", "टायर", "vehicles", "Grips the road.", "Replace tyres when the tread is below 1.6 mm.", ["car-tire"]],
  ["steering wheel", "स्टीयरिंग", "vehicles", "Steers a car.", "Hold it at 9 and 3 o'clock for best control.", ["steering-wheel"]],
  ["auto rickshaw", "ऑटो रिक्शा", "vehicles", "Three-wheeler taxi.", "Ask for the meter, or agree on the fare before the ride."],
  ["bus", "बस", "vehicles", "Public transport for many people.", "Keep your phone and wallet in front pockets in crowds.", ["school-bus"]],
  ["traffic light", "ट्रैफ़िक लाइट", "outdoor", "Controls road traffic.", "Red: stop. Amber: slow down. Green: go carefully.", ["traffic-light"]],
  ["fire hydrant", "फ़ायर हाइड्रेंट", "outdoor", "Water supply for firefighters.", "Never park in front of one.", ["fire-hydrant"]],
  ["license plate", "नंबर प्लेट", "vehicles", "Identifies a registered vehicle.", "India now uses high-security registration plates (HSRP).", ["license-plate"]],
  ["baby stroller", "बच्चा गाड़ी", "home", "Carries a baby on walks.", "Always use the harness and the brakes when stopped.", ["pram"]],
  ["dog", "कुत्ता", "animals", "Loyal pet and companion.", "Vaccinate pets against rabies every year.", ["dog", "greyhound"]],
  ["cat", "बिल्ली", "animals", "Independent pet.", "Deworm and vaccinate pet cats regularly."],
  ["person", "व्यक्ति", "people", "A human being.", "", ["people", "faces-easy-101"]],
];

const seen = new Set();
const objects = V.map(([name, hi, cat, use, tip, caltech = []], id) => {
  if (seen.has(name)) throw new Error(`duplicate: ${name}`);
  seen.add(name);
  return { id, name, hi, cat, use, tip, caltech };
});
writeFileSync(new URL("../public/models/objects-kb.json", import.meta.url), JSON.stringify(objects));
const mapped = objects.filter((o) => o.caltech.length);
console.log(`${objects.length} objects, ${mapped.length} with Caltech-256 training images (${new Set(mapped.flatMap((o) => o.caltech)).size} Caltech classes)`);
